smtp:
  host: 'smtp.mail.ru'
  secure: true
  user: 'horrorspace@mail.ru'
  password: '3zSULzqLCsp7SbyhBUUj'

rabbitmq:
  protocol: 'amqp'
  host: 'localhost'
  port: 5672
  user: 'user'
  password: 'BGNdWquZ'
  durable: true

logger_service:
  queue: 'logger'

mail_service:
  queue: 'mail'