smtp:
  host: 'smtp.gmail.com'
  secure: true
  user: 'qwefgklasm@gmail.com'
  password: 'LOMzXtWT'

rabbitmq:
  protocol: 'amqp'
  host: 'localhost'
  port: 5672
  user: 'user'
  password: 'BGNdWquZ'
  durable: true

logger_service:
  queue: 'logger'

mail_service:
  queue: 'mail'